name: Build/android

on:
  push:
    branches:
      - master
      - "android-ci"
    tags:
      - '*'
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            npm install -g @quasar/cli
            npm install
            echo "creating keystore"
            mkdir keys
            echo "$RELEASE_KEYSTORE" > keys/quasar-release-key.jks
            echo "finishing creating keystore"
            echo "decode passphrase"
            gpg -d --passphrase "$RELEASE_KEYSTORE_PASSPHRASE" --batch keys/quasar-release-key.jks.asc > keys/quasar-release-key.jks
            echo "finishing decoding passphrase"
            quasar build -m android --buildConfig=../build.cordova.json
            find . -name '*.apk'
            mv dist/cordova/android/apk/release/app-release-unsigned.apk dist/cordova/android/apk/release/dadadash-app.apk


      - uses: actions/upload-artifact@v2
        with:
          name: dadadash-app.apk
          path: dist/cordova/android/apk/release/dadadash-app.apk


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/cordova/android/apk/release/dadadash-app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
