name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'


      - name: Install Libraries
        shell: bash
        run: |
          npm install -g @quasar/cli


      - name: Build
        run: |
          quasar build -m spa

      - uses: actions/upload-artifact@v2
        with:
          name: web-spa
          path: disp/spa
