name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Libraries
        shell: bash
        run: |
          npm install -g @quasar/cli
          npm install

      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            ls -lah && \
            cordova platform add android && \
            cordova build --release android
            cp "$(find . -name '*.apk')" .

      - name: Build
        run: |
          quasar build -m spa


