name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Libraries
        shell: bash
        run: |
          npm install -g @quasar/cli


      - name: Build
        run: |
          npm install
          quasar build -m spa

      - uses: actions/upload-artifact@v2
        with:
          name: web-spa
          path: disp/spa
