name: Build/web-spa

on: push
  branches:
    - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Libraries
        shell: bash
        run: |
          npm install -g @quasar/cli
          npm install -g cordova
          npm install


      - name: Build
        run: |
          quasar build -m spa


      - uses: actions/upload-artifact@v2
        with:
          name: web-spa
          path: dist/spa
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: daptin/dadadash:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
